# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acf12ef573fcc0302fd990094ef35fc2d01a1bdd630c046c619768539adcd956605e25aa364cc5f32bb58df9163af428952ba62ae6769799a7c7a3852f0be2e4

test:
  secret_key_base: 58000bbbfdff0e6246e08773e55b11204afc4db8fc3b5debf90ed0a89f53253774b6b5673541e3904eac926b1f9896b75235d570865871d020de2d2d0a3baf9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
